#CALCULAR A ALTURA MÁXIMA DE UM PROJÉTIL SABENDO A VELOCIDADE INICIAL (aleatório)  E O ÂNGULO ( 30,45,60 ) -> aleatorio
#CALCULAR A DISTÂNCIA PERCORRIDA PELO PROJÉTIL
#INSERIR UM JOGO PARA QUE O USUÁRIO INFORME UM POSSÍVEL VALOR DE DISTÂNCIA
#SE ACERTAR, GANHA PONTO
#PLOTAR O GRÁFICO

def menu():
    print("MENU")

print("julio")


#PRINCI, 